version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth
      - main
      - frontend
      
  auth:
    build: ./auth-service
    ports:
      - "5000:5000"  # Добавьте эту строку
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/db
    depends_on:
      - postgres
      
  main:
    build: ./main-service
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
      - AUTH_SERVICE_URL=http://auth:5000
    depends_on:
      - postgres
      - auth

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
